# 7. Write a program to scrap all the available details of top 10 gaming laptops from digit.in.

In [1]:
#lets import all required libraries
import selenium
import pandas as pd
from selenium import webdriver

In [2]:
#lets first connect to the web driver
driver=webdriver.Chrome(r"C://chromedriver.exe")

In [3]:
driver.get('https://www.digit.in/')

In [4]:
url='https://www.digit.in/search/?keyword=gaming%20laptops'

In [5]:
#lets open the webpage through web driver
driver.get(url)

In [14]:
titles=[]

In [15]:
#lets extract all the tags
titles=driver.find_elements_by_xpath("//div[@class='searchProduct-desc']")
titles[0:4]

[<selenium.webdriver.remote.webelement.WebElement (session="e2971d2e0384ff0e958e7ccf5b704829", element="3ac6f3ca-c3bc-464f-8c90-41b507f1c02c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2971d2e0384ff0e958e7ccf5b704829", element="16327ce8-526a-4487-a451-299dbf7e41f4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2971d2e0384ff0e958e7ccf5b704829", element="2ac7dce9-9d6e-4031-b08e-191caea08e30")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2971d2e0384ff0e958e7ccf5b704829", element="fb8d156a-db30-4208-b356-a7801bb6c0bb")>]

In [16]:
for i in titles:
    title=i.text
    job_titles.append(title)
job_titles[0:10]

['HP Envy 15-k006tx',
 'Asus G750JX-CV069P',
 "ASUS G53J - A 3D gamer's delight but we want more",
 'Lenovo IdeaPad Y570',
 'HP Pavilion g6 - Multimedia and gaming on a budget',
 'ASUS ROG Cetra',
 'Truvison TX3271',
 'Lenovo G50-30',
 'Budget gaming laptops',
 'Backpacks for gaming laptops']

# 6. Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 â€“ September 20) from trak.in.

In [2]:
#lets first connect to the web driver
driver1=webdriver.Chrome(r"C://chromedriver.exe")
driver1.get('https://trak.in/')

url='https://trak.in/india-startup-funding-investment-2015/'

#lets open the webpage through web driver
driver1.get(url)

In [3]:
fi_date=[]
startup=[]
industry=[]
vertical=[]
location=[]
name=[]
invetment_type=[]
amount=[]

In [4]:
#lets extract all the tags
date=driver1.find_elements_by_xpath("//td[@class='column-2']")
date[0:4]

[<selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="1ec9fe7f-f217-4a81-9c99-e7fa22c098c0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="ff32309f-52fe-4a19-843e-7f7a89b6071b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="622226b9-b690-4328-bc1e-34481e9798b0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="3336ff1c-d660-4b35-90eb-d45e002c1a19")>]

In [5]:
for i in date:
    title=i.text
    fi_date.append(title)
fi_date[0:4]

['11/02/2021', '22/02/2021', '19/02/2021', '17/02/2021']

In [6]:
start=driver1.find_elements_by_xpath("//td[@class='column-3']")
start[0:4]

[<selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="dc35372b-726f-48d9-950a-c1451586b373")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="dccb6a24-0363-4919-8d5b-9026649e545d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="78282043-5ae7-4eb6-b417-7e711af7c3cc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a500d4fbca5c31f041f98571b5434abe", element="5a576b3d-63f6-43f5-9cc1-8d7b3e2b065c")>]

In [7]:
for i in start:
    title1=i.text
    startup.append(title1)
startup[0:4]

['Doubtnut', 'Zomato', 'Fingerlix', 'Zolve']

In [8]:
indus=driver1.find_elements_by_xpath("//td[@class='column-4']")
for i in indus:
    title2=i.text
    industry.append(title2)
industry[0:4]

['Edu Tech', 'Hospitality', 'Hospitality', 'FinTech']

In [9]:
verti=driver1.find_elements_by_xpath("//td[@class='column-5']")
for i in verti:
    title3=i.text
    vertical.append(title3)
vertical[0:4]

['E-Learning Platform',
 'Online Food Delivery Platform',
 'Semi-cooked food delivery app',
 'Global Neobank Venture']

In [10]:
loca=driver1.find_elements_by_xpath("//td[@class='column-6']")
for i in loca:
    title4=i.text
    location.append(title4)
location[0:4]

['Gurgaon', 'Gurgaon', 'Mumbai', 'Mumbai']

In [11]:
nam=driver1.find_elements_by_xpath("//td[@class='column-7']")
for i in nam:
    title5=i.text
    name.append(title5)
name[0:4]

['SIG Global, Sequoia Capital, WaterBridge Ventures and ON Mauritius',
 'Tiger Global, Kora',
 'Rhodium Trust, Accel Partners and Swiggy',
 'Accel Partners and Lightspeed Venture Partners']

In [16]:
amt=driver1.find_elements_by_xpath("//td[@class='column-9']")
for i in amt:
    title7=i.text
    amount.append(title7)
amount[0:4]

['2,500,000', '250,000,000', '2,747,045.20', '1,50,00,000']

In [24]:
trak=pd.DataFrame({})
trak['dates']=fi_date[45:70]
trak['startups']=startup[45:70]
trak['company']=industry[45:70]
trak['verticals']=vertical[45:70]
trak['locations']=location[45:70]
trak['names']=name[45:70]
trak['amounts']=amount[45:70]

In [25]:
trak

,dates,startups,company,verticals,locations,names,amounts
0,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,"370,000"
1,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...","15,500,000"
2,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...","4,500,000"
3,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.","upto 8,900,000"
4,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group","100,000,000"
5,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,"5,400,000"
6,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,"8,000,000"
7,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,"950,000"
8,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,"32,000,000"
9,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,"23,000,000"
10,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...","1,560,000"
11,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,"30,000,000"
12,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...","1,400,000"
13,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,"upto 15,000,000"
14,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,"6,000,000"
15,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,"10,670,000"
16,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,"16,200,000"
17,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus","5,000,000"
18,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,"1,200,000,000"
19,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,"100,000,000"
20,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,"934,160"
21,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...","1,700,000"
22,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,"3,300,000"
23,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,"400,000"
24,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,"974,200"

# 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [162]:
#lets first connect to the web driver
driver4=webdriver.Chrome(r"C://chromedriver.exe")
driver4.get('https://en.wikipedia.org/')

url='https://en.wikipedia.org/wiki/List_of_extreme_points_of_India'

#lets open the webpage through web driver
driver4.get(url)

In [163]:
city=[]
latlong=[]

In [164]:
name=driver4.find_elements_by_xpath("//td[@class='fn org']")
for i in name:
    title2=i.text
    city.append(title2)
city[0:4]

['East of Indira Col at Siachen Glacier',
 'East of Kilik Pass in the Karakoram Mountains on Xinjiang-Gilgit-Baltistan border',
 'Indira Point on the southernmost end of Great Nicobar Island of the Nicobar Islands',
 'Cape Comorin near Kanyakumari']

In [166]:
cord=driver4.find_elements_by_xpath("//span[@class='geo-dec']")
for i in cord:
    title3=i.text
    latlong.append(title3)
latlong[0:4]

['35.674521Â°N 76.844485Â°E',
 '37.08586Â°N 74.70291Â°E',
 '33.25615Â°N 76.79877Â°E',
 '6.74678Â°N 93.84260Â°E']

In [169]:
cordinate=pd.DataFrame({})
cordinate['name']=city[0:10]
cordinate['lat_long']=latlong[0:10]

In [170]:
cordinate

                                                name                 lat_long
0              East of Indira Col at Siachen Glacier  35.674521Â°N 76.844485Â°E
1  East of Kilik Pass in the Karakoram Mountains ...    37.08586Â°N 74.70291Â°E
2  Indira Point on the southernmost end of Great ...    33.25615Â°N 76.79877Â°E
3                      Cape Comorin near Kanyakumari     6.74678Â°N 93.84260Â°E
4  Southeast of Dong (before Kibithu in Anjaw dis...     8.06890Â°N 77.55230Â°E
5  Chaukan Pass, east of Vijaynagar in Changlang ...    28.01168Â°N 97.39564Â°E
6                        Sir Creek in Kutch district    27.13611Â°N 97.16575Â°E
7                                      Kangchenjunga      23.6261Â°N 68.1941Â°E
8                                                 K2    27.70250Â°N 88.14833Â°E
9                                         Nanda Devi    35.88250Â°N 76.51333Â°E

# 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com

In [59]:
#lets first connect to the web driver
driver2=webdriver.Chrome(r"C://chromedriver.exe")
driver2.get('https://www.flipkart.com/')

url='https://www.flipkart.com/search?q=oneplus%20&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'

#lets open the webpage through web driver
driver2.get(url)

In [60]:
rating=[]
price=[]
mobile=[]
desc=[]

In [61]:
d=driver2.find_elements_by_xpath("//li[@class='rgWa7D']")
for i in d:
    title2=i.text
    desc.append(title2)
desc[0:4]

['Netflix|Prime Video|Disney+Hotstar|Youtube',
 'Operating System: Android',
 'Full HD 1920 x 1080 Pixels',
 '20 W Speaker Output']

In [62]:
brand=driver2.find_elements_by_xpath("//div[@class='_4rR01T']")
for i in brand:
    title2=i.text
    mobile.append(title2)
mobile[0:4]

['OnePlus Y Series 108 cm (43 inch) Full HD LED Smart Android TV',
 'OnePlus Y Series 80 cm (32 inch) HD Ready LED Smart Android TV',
 'OnePlus U Series 138.8 cm (55 inch) Ultra HD (4K) LED Smart Android TV',
 'OnePlus Q1 Series 138.8 cm (55 inch) QLED Ultra HD (4K) Smart Android TV']

In [63]:
rev=driver2.find_elements_by_xpath("//div[@class='gUuXy-']")
for i in rev:
    title3=i.text
    rating.append(title3)
rating[0:4]

['4.316,043 Ratings & 1,427 Reviews',
 '4.316,043 Ratings & 1,427 Reviews',
 '4.394 Ratings & 8 Reviews',
 '4.5897 Ratings & 129 Reviews']

In [64]:
cost=driver2.find_elements_by_xpath("//div[@class='_30jeq3 _1_WHN1']")
for i in cost:
    title4=i.text
    price.append(title4)
price[0:4]

['â‚¹25,999', 'â‚¹15,499', 'â‚¹52,999', 'â‚¹62,899']

In [65]:
phone=pd.DataFrame({})
phone['mobiles']=mobile[0:40]
phone['review&rating']=rating[0:40]
phone['prices']=price[0:40]
phone['description']=desc[0:40]

In [66]:
phone

,mobiles,review&rating,prices,description
0,OnePlus Y Series 108 cm (43 inch) Full HD LED ...,"4.316,043 Ratings & 1,427 Reviews","â‚¹25,999",Netflix|Prime Video|Disney+Hotstar|Youtube
1,OnePlus Y Series 80 cm (32 inch) HD Ready LED ...,"4.316,043 Ratings & 1,427 Reviews","â‚¹15,499",Operating System: Android
2,OnePlus U Series 138.8 cm (55 inch) Ultra HD (...,4.394 Ratings & 8 Reviews,"â‚¹52,999",Full HD 1920 x 1080 Pixels
3,OnePlus Q1 Series 138.8 cm (55 inch) QLED Ultr...,4.5897 Ratings & 129 Reviews,"â‚¹62,899",20 W Speaker Output
4,OnePlus Bullets Wireless Z Bluetooth Headset,"4.42,49,481 Ratings & 26,027 Reviews","â‚¹1,993",60 Hz Refresh Rate
5,OnePlus Bullets Wireless Z Bass Edition Blueto...,"4.491,302 Ratings & 9,409 Reviews","â‚¹1,899",2 x HDMI | 2 x USB
6,OnePlus Bullets Wireless Z Bass Edition Blueto...,"4.491,302 Ratings & 9,409 Reviews","â‚¹1,899",LED
7,OnePlus Bullets Wireless Z Bluetooth Headset,"4.42,49,481 Ratings & 26,027 Reviews","â‚¹1,999",1 Year Comprehensive Warranty and Additional 1...
8,OnePlus Buds Z Bluetooth Headset,"4.319,357 Ratings & 2,036 Reviews","â‚¹2,699",Netflix|Prime Video|Disney+Hotstar|Youtube
9,OnePlus Buds Z Bluetooth Headset,"4.319,357 Ratings & 2,036 Reviews","â‚¹2,699",Operating System: Android
10,"OnePlus 10000 mAh Power Bank (18 W, Fast Charg...","4.36,724 Ratings & 458 Reviews","â‚¹1,099",HD Ready 1366 x 768 Pixels
11,"OnePlus 10000 mAh Power Bank (18 W, Fast Charg...","4.36,724 Ratings & 458 Reviews","â‚¹1,099",20 W Speaker Output
12,OnePlus Band,"4.27,553 Ratings & 1,152 Reviews","â‚¹2,379",60 Hz Refresh Rate
13,jkg DASH CHARGING CABLE 6 A 1 m ORIGINAL USB T...,4.4271 Ratings & 52 Reviews,â‚¹359,2 x HDMI | 2 x USB
14,OnePlus Buds Z Bluetooth Headset,"4.319,357 Ratings & 2,036 Reviews","â‚¹3,699",LED
15,OnePlus Buds Bluetooth Headset,"4.216,595 Ratings & 1,785 Reviews","â‚¹4,690",1 Year Comprehensive Warranty and Additional 1...
16,Flipkart SmartBuy Edge To Edge Tempered Glass ...,"3.41,083 Ratings & 138 Reviews",â‚¹199,Netflix|Prime Video|Disney+Hotstar|Youtube
17,Tdoc Wall Charger Accessory Combo for One_plus...,3.9180 Ratings & 34 Reviews,â‚¹599,Operating System: Android
18,GadgetM Back Cover for OnePlus Nord,4.4125 Ratings & 16 Reviews,â‚¹259,Ultra HD (4K) 3840 x 2160 Pixels
19,OnePlus Buds Bluetooth Headset,"4.216,595 Ratings & 1,785 Reviews","â‚¹4,690",30 W Speaker Output
20,KWINE CASE Back Cover for OnePlus Nord,"4.41,220 Ratings & 156 Reviews",â‚¹259,60 Hz Refresh Rate
21,OnePlus Buds Bluetooth Headset,"4.216,595 Ratings & 1,785 Reviews","â‚¹4,690",3 x HDMI | 2 x USB
22,Gorilla Original Edge To Edge Tempered Glass f...,4.49 Ratings & 2 Reviews,â‚¹260,LED
23,SHINESTAR. Back Cover for Oneplus Nord,4.2190 Ratings & 23 Reviews,â‚¹259,1 Year Comprehensive Warranty and Additional 1...
24,VaiMi Tempered Glass Guard for OnePlus Nord,4395 Ratings & 48 Reviews,â‚¹259,Netflix|Prime Video|Disney+Hotstar|Youtube
25,Colorcase Front & Back Case for OnePlus Buds,4499 Ratings & 37 Reviews,â‚¹299,Operating System: Android
26,Mobile Mart Back Cover for OnePlus Nord,4.2842 Ratings & 80 Reviews,â‚¹259,Ultra HD (4K) 3840 x 2160 Pixels
27,Case U Edge To Edge Tempered Glass for OnePlus...,"3.62,204 Ratings & 332 Reviews",â‚¹499,50 W Speaker Output
28,Case Plus Edge To Edge Tempered Glass for Onep...,3.929 Ratings & 19 Reviews,â‚¹449,60 Hz Refresh Rate
29,Flipkart SmartBuy Back Cover for Oneplus Nord,4.3250 Ratings & 26 Reviews,â‚¹149,4 x HDMI | 2 x USB
30,GadgetM Back Cover for OnePlus Nord,4.3128 Ratings & 12 Reviews,â‚¹259,QLED
31,Dainty Back Camera Lens Glass Protector for On...,3.6142 Ratings & 15 Reviews,â‚¹140,1 Year Comprehensive Warranty on the Product a...
32,Power Back Cover for OnePlus 6,4.4476 Ratings & 42 Reviews,â‚¹199,With Mic:Yes
33,Flipkart SmartBuy Back Cover for OnePlus Nord,3.9311 Ratings & 31 Reviews,â‚¹229,Bluetooth version: 5
34,"SWAPKART Red, White Type C to 3.5mm Splitter S...",3.9273 Ratings & 54 Reviews,â‚¹299,Wireless range: 10 m
35,FINCH Screen Guard for OnePlus Band,3.4165 Ratings & 33 Reviews,â‚¹149,Warp charge: 10 minute charge for 10 hours of ...
36,"VAKIBO Back Cover for OnePlus 3, OnePlus 3T",4.2427 Ratings & 65 Reviews,â‚¹199,20 Hours playtime
37,SAPCASE Back Cover for Oneplus 8T,4.393 Ratings & 10 Reviews,â‚¹259,Low Latency mode
38,SHINESTAR. Back Cover for Oneplus Nord,4.3350 Ratings & 41 Reviews,â‚¹259,Press play with Magnetic Control
39,GadgetM Back Cover for OnePlus Nord,4.4172 Ratings & 19 Reviews,â‚¹259,1 Year Warranty

# 3. Write a python program to access the search bar and search button on images.google.com

In [90]:
#lets first connect to the web driver
driver5=webdriver.Chrome(r"C://chromedriver.exe")
driver5.get('https://images.google.com/')

url='https://www.google.com/search?q=cars&tbm=isch&sxsrf=ALeKk02rRqSeBmHtl9YdDXWcFR_8kMV0HA%3A1618469291320&source=hp&biw=1366&bih=625&ei=q-F3YPWtEdKO4-EPxM-WsAw&oq=cars&gs_lcp=CgNpbWcQAzIECCMQJzIFCAAQsQMyBQgAELEDMgIIADIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADoHCCMQ6gIQJzoICAAQsQMQgwFQn2NYwndg_XhoAnAAeACAAXiIAZsEkgEDMC41mAEAoAEBqgELZ3dzLXdpei1pbWewAQo&sclient=img&ved=0ahUKEwi1r7_50__vAhVSxzgGHcSnBcYQ4dUDCAc&uact=5'
url1='https://www.google.com/search?q=fruit&tbm=isch&sxsrf=ALeKk03RTTMZZJrtTuTwGb3_RveeRIEKVQ%3A1618469862702&source=hp&biw=1366&bih=625&ei=5uN3YJTLKMPF4-EPpJSEoAI&oq=fruit&gs_lcp=CgNpbWcQAzIICAAQsQMQgwEyBQgAELEDMggIABCxAxCDATIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQM6BAgjECc6AggAUM8VWN4nYNYpaAFwAHgAgAG-AYgBvwaSAQMwLjaYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img&ved=0ahUKEwiU1vmJ1v_vAhXD4jgGHSQKASQQ4dUDCAc&uact=5'
url2='https://www.google.com/search?q=machine+learning&tbm=isch&sxsrf=ALeKk028NTeyQkhMh9d5jvjmbeVzyZeqpg%3A1618469881695&source=hp&biw=1366&bih=625&ei=-eN3YJmMKN6R4-EP5Juu0Ak&oq=machine&gs_lcp=CgNpbWcQARgAMgUIABCxAzIFCAAQsQMyBQgAELEDMgUIABCxAzIICAAQsQMQgwEyBQgAELEDMgIIADIFCAAQsQMyAggAMgUIABCxAzoECCMQJ1CtBlivE2DfIGgAcAB4AIABlwGIAe0GkgEDMC43mAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img'

#lets open the webpage through web driver
driver5.get(url+url1+url2)

In [91]:
img_car=[]

for i in range(0,10):
    for j in driver5.find_elements_by_xpath("//div[@class='bRMDJf islir']/img"):
        img_car.append(j.get_attribute("src"))

In [92]:
img_fruit=[]

for i in range(0,10):
    for j in driver5.find_elements_by_xpath("//div[@class='bRMDJf islir']/img"):
        img_fruit.append(j.get_attribute("src"))

In [94]:
img_ml=[]

for i in range(0,10):
    for j in driver5.find_elements_by_xpath("//div[@class='bRMDJf islir']/img"):
        img_ml.append(j.get_attribute("src"))

In [95]:
print(len(img_car),len(img_fruit),len(img_ml))

980 490 490

In [96]:
img=pd.DataFrame({})
img['cars']=img_car[0:100]
img['fruits']=img_fruit[0:100]
img['machine_learning']=img_ml[0:100]

In [97]:
img

,cars,fruits,machine_learning
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
...,...,...,...
95,None,None,None
96,None,None,None
97,None,None,None
98,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
99,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."

# 1. Write a python program which searches all the product under a particular product from www.amazon.in.

# 2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a dataframe and csv.

In [104]:
#lets first connect to the web driver
driver6=webdriver.Chrome(r"C://chromedriver.exe")
driver6.get('https://www.amazon.in/')
search=input('driver6.find_element_by_id:' )
input('search.send_keys:' )

driver6.find_element_by_id:twotabsearchtextbox
search.send_keys:mobiles

'mobiles'

In [128]:
url='https://www.amazon.in/s?k=mobiles&ref=nb_sb_noss_2'
url1='https://www.amazon.in/s?k=mobiles&page=2&qid=1618478558&ref=sr_pg_2'
url3='https://www.amazon.in/s?k=mobiles&page=3&qid=1618478629&ref=sr_pg_3'

driver6.get(url+url1+url2)

In [129]:
name=[]
price=[]
rating=[]

In [130]:
brand=driver6.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in brand:
    title2=i.text
    name.append(title2)
name[0:4] 
brand1=driver6.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in brand1:
    title21=i.text
    name.append(title21)
name[0:4] 
brand2=driver6.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in brand2:
    title22=i.text
    name.append(title22)
name[0:4]

['Samsung Galaxy M31 (Space Black, 6GB RAM, 128GB Storage)',
 'Panasonic Eluga i7 (2GB RAM, 16GB Storage, Finger Print Sensor, 4000mAh Battery) (Black)',
 'Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB Storage)',
 'Redmi 9A (Sea Blue, 2GB Ram, 32GB Storage) | 2GHz Octa-core Helio G25 Processor']

In [131]:
cost=driver6.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in cost:
    title4=i.text
    price.append(title4)
price[0:4]
cost1=driver6.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in cost1:
    title41=i.text
    price.append(title41)
price[0:4]
cost2=driver6.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in cost2:
    title42=i.text
    price.append(title42)
price[0:4]

['16,499', '5,004', '12,499', '6,799']

In [132]:
rev=driver6.find_elements_by_xpath("//span[@class='a-size-base']")
for i in rev:
    title3=i.text
    rating.append(title3)
rating[0:4]
rev1=driver6.find_elements_by_xpath("//span[@class='a-size-base']")
for i in rev1:
    title31=i.text
    rating.append(title31)
rating[0:4]
rev2=driver6.find_elements_by_xpath("//span[@class='a-size-base']")
for i in rev2:
    title32=i.text
    rating.append(title32)
rating[0:4]

['166,082', '2,563', '117,731', '32,361']

In [133]:
mobile=pd.DataFrame({})
mobile['titles']=name[0:48]
mobile['ratings']=rating[0:48]
mobile['prices']=price[0:48]

In [134]:
mobile

                                               titles  ratings  prices
0   Samsung Galaxy M31 (Space Black, 6GB RAM, 128G...  166,082  16,499
1   Panasonic Eluga i7 (2GB RAM, 16GB Storage, Fin...    2,563   5,004
2   Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB...  117,731  12,499
3   Redmi 9A (Sea Blue, 2GB Ram, 32GB Storage) | 2...   32,361   6,799
4   Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...    4,139  10,999
5   Redmi 9A (Nature Green, 3GB Ram, 32GB Storage)...   32,361   7,499
6   Redmi Note 9 (Arctic White, 4GB RAM, 64GB Stor...   47,105  10,999
7       Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage)   27,705   8,799
8   Redmi Note 9 (Aqua Green, 4GB RAM, 64GB Storag...   47,105  10,999
9   Redmi 9A (Midnight Black, 2GB RAM, 32GB Storag...   32,361   6,799
10  Samsung Galaxy M12 (White,4GB RAM, 64GB Storag...    4,139  10,999
11  Samsung Galaxy M12 (Black,6GB RAM, 128GB Stora...    4,139  13,499
12  Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2...   32,361   7,499
13  Samsung Galaxy M12 (Black,4GB RAM, 64GB Storag...    4,139  10,999
14     Redmi 9 (Sporty Orange, 4GB RAM, 64GB Storage)   27,705   8,799
15  Redmi Note 10 (Shadow Black, 6GB RAM, 128GB St...    1,731  13,999
16  Samsung Galaxy M31 (Space Black, 6GB RAM, 128G...  166,082  16,499
17  Panasonic Eluga i7 (2GB RAM, 16GB Storage, Fin...    2,563   5,004
18  Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB...  117,731  12,499
19  Redmi 9A (Sea Blue, 2GB Ram, 32GB Storage) | 2...   32,361   6,799
20  Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...    4,139  10,999
21  Redmi 9A (Nature Green, 3GB Ram, 32GB Storage)...   32,361   7,499
22  Redmi Note 9 (Arctic White, 4GB RAM, 64GB Stor...   47,105  10,999
23      Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage)   27,705   8,799
24  Redmi Note 9 (Aqua Green, 4GB RAM, 64GB Storag...   47,105  10,999
25  Redmi 9A (Midnight Black, 2GB RAM, 32GB Storag...   32,361   6,799
26  Samsung Galaxy M12 (White,4GB RAM, 64GB Storag...    4,139  10,999
27  Samsung Galaxy M12 (Black,6GB RAM, 128GB Stora...    4,139  13,499
28  Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2...   32,361   7,499
29  Samsung Galaxy M12 (Black,4GB RAM, 64GB Storag...    4,139  10,999
30     Redmi 9 (Sporty Orange, 4GB RAM, 64GB Storage)   27,705   8,799
31  Redmi Note 10 (Shadow Black, 6GB RAM, 128GB St...    1,731  13,999
32  Samsung Galaxy M31 (Space Black, 6GB RAM, 128G...  166,082  16,499
33  Panasonic Eluga i7 (2GB RAM, 16GB Storage, Fin...    2,563   5,004
34  Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB...  117,731  12,499
35  Redmi 9A (Sea Blue, 2GB Ram, 32GB Storage) | 2...   32,361   6,799
36  Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...    4,139  10,999
37  Redmi 9A (Nature Green, 3GB Ram, 32GB Storage)...   32,361   7,499
38  Redmi Note 9 (Arctic White, 4GB RAM, 64GB Stor...   47,105  10,999
39      Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage)   27,705   8,799
40  Redmi Note 9 (Aqua Green, 4GB RAM, 64GB Storag...   47,105  10,999
41  Redmi 9A (Midnight Black, 2GB RAM, 32GB Storag...   32,361   6,799
42  Samsung Galaxy M12 (White,4GB RAM, 64GB Storag...    4,139  10,999
43  Samsung Galaxy M12 (Black,6GB RAM, 128GB Stora...    4,139  13,499
44  Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2...   32,361   7,499
45  Samsung Galaxy M12 (Black,4GB RAM, 64GB Storag...    4,139  10,999
46     Redmi 9 (Sporty Orange, 4GB RAM, 64GB Storage)   27,705   8,799
47  Redmi Note 10 (Shadow Black, 6GB RAM, 128GB St...    1,731  13,999